### ISSUE TITLE
Error parsing an activity's exotic_payload

### ISSUE THREAD

**Issue by webcracy** [manybots/manybots#5]
```
NoMethodError in ActivitiesController#index

undefined method `keys' for nil:NilClass
Rails.root: /home/niko/Work/manybots

Application Trace | Framework Trace | Full Trace
app/models/activity.rb:322:in `exotic_payload'
app/models/activity.rb:384:in `as_activity_v1_0'
```

(thx @NikoRoberts)

**Comment by webcracy** [comment]
Fixed with fcd4582af8157c5a95aa2a14ee9c87583e86b72a
